# Generated by Django 4.1.8 on 2023-05-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_changed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
