# Generated by Django 4.1.13 on 2024-01-24 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
