# Generated by Django 4.1.13 on 2024-01-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sp_id',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
