# Generated by Django 4.1.13 on 2024-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
