# Generated by Django 4.1.13 on 2024-01-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
    ]
