# Generated by Django 4.1.13 on 2024-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
